#!/bin/sh

unzip -o hoyttpng.zip
perl -pi -e 's/private static final String IMG_PROMO_APP_NUMBER_VALUE = ".";/private static final String IMG_PROMO_APP_NUMBER_VALUE = "1";/gmi' src/com/hoy/helpers/ImageHelper.java
echo "Now make APK for i=1 (teachingtango)"
